module.exports = [
    'Telur Ayam',
    'Telur Bebek',
    'Gula',
    'Garam',
    'Nasi',
    'Mie',
    'Teh',
    'Jeruk',
    'Es Batu',
    'Cabe',
    'Saus',
    'Penyedap Rasa',
    'Daging Ayam',
    'Daging Sapi',
    'Wortel',
    'Kubis',
    'Sawi',
    'Lobak',
    'Bawang Putih',
    'Bawang Merah',
    'Bawang Bombay',
]