module.exports = [
    'The Ligning Hour',
    'Trained for Sin',
    'Widow of Terror',
    'Forge of the Heart',
    'The Eye of the Magician',
    'Cleric Voyage',
    '2015: Oblivion',
    'Spare Girl',
    'Lacy and Racy',
    'Mermaids and Siren',
    'Clue of the 13 Violins',
    'Tried for Carnage',
    'Eclipse of Uranus',
    'The Colossus in the Vale',
    'Sky Full of Starts',
    'White Noon',
    'Built for Error',
    'The Raven Daemon',
    'Metal Colony',
    '2099: Extinction',
    'Atlantis Recoiling',
    'Case of the Prize Boa',
]